### PR TITLE
Proposed patch

### PR DESCRIPTION
**Pull request by snowball77**
Proposed patch for SIMULIZAR-96

### CODE REVIEW

**Comment by snowball77** [comment]
I agree. It seems to me that saving is a very old legacy call. Could you just remove it?

**Comment by snowball77** [comment]
I agree. It seems to me that saving is a very old legacy call. Could you just remove it?

**Comment by sdkrach** [comment]
Should work once  PalladioSimulator/Palladio-Analyzer-Framework#1 is merged.

**Comment by dwerle** [comment]
I propose to do this via the org.palladiosimulator.simulizar.launcher.modelload extension point, see #8. However, for this to work, the EventsTransformationJob has to be changed slighty. See the pull request for more information.

**Comment by snowball77** [comment]
Yes, I saw it later. Looks all fine to me, I reviewed all patches and approved them. If all is fine, can you pull the code into master?

**Comment by klinakuf** [comment]
What is still open in this issue?

**Comment by dwerle** [comment]
In my opinion, this is subsumed in #8, which also includes the EventsTransformationJob in the SimuLizar run configuration.

**Pull request closed without merging**
