### PR TITLE
Deleted ModelAccess class

### PR DESCRIPTION
**Pull request by max-sch**

### CODE REVIEW

**Comment by max-sch** [comment]
Fixes:

- Strings instead of URIs: I could only identify classes in which the model file or locations are fetched from the simulizar workflow configuration object; the strings, however, are then immediately converted to URIs.
- It does not compile: I could not reproduce this error, the code can be built and contains no compilation errors.
- Documentation of PCMModelManager: Documentation has been added.

**Comment by snowball77** [comment]
I looked through the code, as far as I can tell. For me the patch could be merged once there is an updated pull request including the docu.

**Comment by seiferma** [comment]
I kindly ask to delay the merging until the PCM 4.2 release.

**Comment by seiferma** [comment]
We did the release, so there is no blocker for merging this PR from my side anymore.

**Pull request merged**
